=== Sam05dz/DSS/CVTEQUE.dtd
<!-- Mini Projet XML - Module : Les Données Semi-structurées -Houssam HAMOUDA -->

<!ELEMENT CV ( Entête ,Poste_actuel ,diplôme_obtenues ,Stages ,
Compétences_techniques,Langues ,Loisirs ,CVI  ) >
<!ELEMENT ID ( nom |prénom  )*>
<!ATTLIST CV ID NMTOKEN #REQUIRED >
<!ELEMENT Entête ( nom, prénom, date_et_lieu_de_naissance, adresse_émail, image ) >

<!ELEMENT Poste_actuel ( poste_actuel+ ) >
<!ELEMENT diplôme_obtenues ( diplôme_obtenue+ ) >

<!ELEMENT Stages ( stage+ ) >
<!ELEMENT 
Compétences_techniques ( compétence_technique+ ) >
<!ELEMENT Langues ( langue+ )>
<!ELEMENT Loisirs ( loisir+ )>
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prénom (#PCDATA) >

<!ELEMENT date_et_lieu_de_naissance (#PCDATA) >

<!ELEMENT adresse_émail (#PCDATA) >

<!ELEMENT image (#PCDATA) >
<!ELEMENT diplôme_obtenue ( #PCDATA ) >
<!ELEMENT poste_actuel (#PCDATA) >
<!ELEMENT compétence_technique (#PCDATA) >
<!ELEMENT stage (#PCDATA) >
<!ELEMENT langue (#PCDATA) >
<!ELEMENT loisir (#PCDATA) >

=== Sam05dz/DSS/CVTEQUE.xml
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE CV SYSTEM "C:\Users\DEW-INFO\Desktop\cvtech\CVTEQUE.dtd">
<CV ID="VALUE">
	<Entête>
		<nom>VALUE</nom>
		<prénom>VALUE</prénom>
		<date_et_lieu_de_naissance>VALUE</date_et_lieu_de_naissance>
		<adresse_émail>VALUE</adresse_émail>
		<image>VALUE</image>
	</Entête>
	<Poste_actuel>
		<poste_actuel>VALUE</poste_actuel>
	</Poste_actuel>
	<diplôme_obtenues>
		<diplôme_obtenue>VALUE</diplôme_obtenue>
	</diplôme_obtenues>
	<Stages>
		<stage>VALUE</stage>
	</Stages>
	<Compétences_techniques>
		<compétence_technique>VALUE</compétence_technique>
	</Compétences_techniques>
	<Langues>
		<langue>VALUE</langue>
	</Langues>
	<Loisirs>
		<loisir>VALUE</loisir>
	</Loisirs>
</CV>
